CREATE TABLE IF NOT EXISTS OURP_ORGANIZATION (
	ORG_ID					VARCHAR(32) NOT NULL,
	PRNT_ID					VARCHAR(32),
	ORG_NAME				VARCHAR(128),
	SHORT_NAME				VARCHAR(64),
	ORG_NATURE				VARCHAR(32),
	INTRODUCTION			VARCHAR(512),
	ADDRESS					VARCHAR(256),
	POSTCODE				VARCHAR(8),
	CNTCT_PERSON			VARCHAR(32),
	CNTCT_PHONE				VARCHAR(32),
	PRIMARY KEY (ORG_ID));

CREATE TABLE IF NOT EXISTS OURP_USER (
	USER_ID					VARCHAR(32) NOT NULL,
	USER_PWD				VARCHAR(128),
	PWD_DIGEST_ALGORITHM	VARCHAR(32),
	FIRST_NAME				VARCHAR(32),
	LAST_NAME				VARCHAR(32),
	NICK_NAME				VARCHAR(32),
	IDCARD					VARCHAR(32),
	EMAIL					VARCHAR(128),
	PHONE					VARCHAR(32),
	ADDRESS					VARCHAR(256),
	IS_VALID				SMALLINT(1) NOT NULL DEFAULT 1,	
	PRIMARY KEY (USER_ID));
	
CREATE TABLE IF NOT EXISTS OURP_ROLE (
	ROLE_ID					VARCHAR(32) NOT NULL,
	ROLE_NAME				VARCHAR(64),
	AUTH_PERMISSIONS		VARCHAR(4608),
	AUTH_ORGANIZATIONS		VARCHAR(4608),
	PRIMARY KEY (ROLE_ID));
	
CREATE TABLE IF NOT EXISTS OURP_PERMISSION (
	CODE				VARCHAR(8) NOT NULL,
	NAME				VARCHAR(64),
	PRNT_CODE			VARCHAR(8),
	PRIMARY KEY (CODE));

	